import { createElement } from 'lwc';
import BoatSearchForm from 'c/boatSearchForm';

describe('c-boat-search-form', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-boat-search-form', {
            is: BoatSearchForm
        });

        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});