import { createElement } from 'lwc';
import BoatAddReviewForm from 'c/boatAddReviewForm';

describe('c-boat-add-review-form', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-boat-add-review-form', {
            is: BoatAddReviewForm
        });

        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});